export const EMAIL_TYPES = {
    VERIFY_OTP: "VERIFY_OTP",
    LOGIN_OTP: "LOGIN_OTP",
    WELCOME: "WELCOME",
    PASSWORD_RESET_OTP: "PASSWORD_RESET_OTP",
    USER_APPROVAL: "USER_APPROVAL",
    USER_BAN: "USER_BAN",
    HIGH_ERROR_RATE_ALERT: "HIGH_ERROR_RATE_ALERT",
    LOGIN_ALERT: "LOGIN_ALERT",
    TWO_FACTOR_OTP: "TWO_FACTOR_OTP",
    VIDEO_READY: "VIDEO_READY",
} as const;

export type EmailType =
    (typeof EMAIL_TYPES)[keyof typeof EMAIL_TYPES];
