export enum ERROR_CODE {
    VALIDATION_ERROR = "VALIDATION_ERROR",
    NOT_FOUND = "NOT_FOUND",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE",
    DATABASE_ERROR = "DATABASE_ERROR",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
    ACCOUNT_PENDING_APPROVAL = "ACCOUNT_PENDING_APPROVAL",
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
    ACCOUNT_NOT_APPROVED = "ACCOUNT_NOT_APPROVED",
    TOKEN_EXPIRED = "TOKEN_EXPIRED"

}
