// src/constants/rolePermissions.ts
import { ROLES } from "./roles.js";
import { PERMISSIONS } from "./permissions.js";

// Default permissions per role
export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
    [ROLES.ADMIN]: Object.values(PERMISSIONS),

    [ROLES.MANAGER]: [
        PERMISSIONS.READ_USER,
        PERMISSIONS.READ_SELF,
        PERMISSIONS.UPDATE_SELF,
        PERMISSIONS.MANAGE_USER, // limited user management
        PERMISSIONS.READ_COURSE,
        PERMISSIONS.READ_OWN_COURSE,
        PERMISSIONS.ENROLL_COURSE,
        PERMISSIONS.UNENROLL_COURSE,
        PERMISSIONS.VIEW_REPORTS,
        PERMISSIONS.VIEW_DASHBOARD,
        PERMISSIONS.SEND_MESSAGES,
        PERMISSIONS.READ_MESSAGES,
    ],

    [ROLES.INSTRUCTOR]: [
        PERMISSIONS.READ_SELF,
        PERMISSIONS.UPDATE_SELF,
        PERMISSIONS.READ_COURSE,
        PERMISSIONS.READ_OWN_COURSE,
        PERMISSIONS.WRITE_COURSE,
        PERMISSIONS.UPDATE_COURSE,
        PERMISSIONS.PUBLISH_COURSE,
        PERMISSIONS.UNPUBLISH_COURSE,
        PERMISSIONS.ASSIGN_INSTRUCTOR,
        PERMISSIONS.VIEW_ENROLLMENTS,
        PERMISSIONS.SEND_MESSAGES,
        PERMISSIONS.READ_MESSAGES,
    ],

    [ROLES.SUPPORT]: [
        PERMISSIONS.READ_USER,
        PERMISSIONS.READ_SELF,
        PERMISSIONS.UPDATE_SELF,
        PERMISSIONS.SEND_MESSAGES,
        PERMISSIONS.READ_MESSAGES,
        PERMISSIONS.MANAGE_NOTIFICATIONS,
    ],

    [ROLES.STUDENT]: [
        PERMISSIONS.READ_SELF,
        PERMISSIONS.READ_OWN_COURSE,
        PERMISSIONS.ENROLL_COURSE,
        PERMISSIONS.UNENROLL_COURSE,
        PERMISSIONS.SEND_MESSAGES,
        PERMISSIONS.READ_MESSAGES,
    ],
};
