import { PERMISSIONS } from "./permissions.js";
import { ROLES } from "./roles.js";

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
    [ROLES.ADMIN.code]: Object.values(PERMISSIONS).map(p => p.code),

    [ROLES.MANAGER.code]: [
        PERMISSIONS.READ_USER.code,
        PERMISSIONS.READ_SELF.code,
        PERMISSIONS.UPDATE_SELF.code,
        PERMISSIONS.MANAGE_USER.code,
        PERMISSIONS.READ_COURSE.code,
        PERMISSIONS.READ_OWN_COURSE.code,
        PERMISSIONS.ENROLL_COURSE.code,
        PERMISSIONS.UNENROLL_COURSE.code,
        PERMISSIONS.VIEW_REPORTS.code,
        PERMISSIONS.VIEW_DASHBOARD.code,
        PERMISSIONS.SEND_MESSAGES.code,
        PERMISSIONS.READ_MESSAGES.code,
        PERMISSIONS.START_LIVE_STREAM.code,
        PERMISSIONS.END_LIVE_STREAM.code,
        PERMISSIONS.SCHEDULE_LIVE_STREAM.code,
    ],

    [ROLES.INSTRUCTOR.code]: [
        PERMISSIONS.READ_SELF.code,
        PERMISSIONS.UPDATE_SELF.code,
        PERMISSIONS.READ_COURSE.code,
        PERMISSIONS.READ_OWN_COURSE.code,
        PERMISSIONS.WRITE_COURSE.code,
        PERMISSIONS.UPDATE_COURSE.code,
        PERMISSIONS.PUBLISH_COURSE.code,
        PERMISSIONS.UNPUBLISH_COURSE.code,
        PERMISSIONS.ASSIGN_INSTRUCTOR.code,
        PERMISSIONS.VIEW_ENROLLMENTS.code,
        PERMISSIONS.SEND_MESSAGES.code,
        PERMISSIONS.READ_MESSAGES.code,
        PERMISSIONS.START_LIVE_STREAM.code,
        PERMISSIONS.END_LIVE_STREAM.code,
        PERMISSIONS.SCHEDULE_LIVE_STREAM.code,
    ],

    [ROLES.SUPPORT.code]: [
        PERMISSIONS.READ_USER.code,
        PERMISSIONS.READ_SELF.code,
        PERMISSIONS.UPDATE_SELF.code,
        PERMISSIONS.SEND_MESSAGES.code,
        PERMISSIONS.READ_MESSAGES.code,
        PERMISSIONS.MANAGE_NOTIFICATIONS.code,
    ],

    [ROLES.STUDENT.code]: [
        PERMISSIONS.READ_SELF.code,
        PERMISSIONS.READ_OWN_COURSE.code,
        PERMISSIONS.ENROLL_COURSE.code,
        PERMISSIONS.UNENROLL_COURSE.code,
        PERMISSIONS.SEND_MESSAGES.code,
        PERMISSIONS.READ_MESSAGES.code,
        PERMISSIONS.VIEW_LIVE_STREAM.code,
    ],
};
